### PR TITLE
Added `socket.id` property

### PR DESCRIPTION
**Pull request by rase-**
Closes https://github.com/Automattic/socket.io-client/issues/681

### CODE REVIEW

**Comment by rauchg** [comment]
We need a test that the `socket.id` gets
- cleared upon disconnection
- changes upon reconnection

And we need to document the API and its behavior.

**Comment by davidrinnan** [comment]
I used the previous socket.sessionId which broke when I upgraded from 0.9(ish) to 1+ (1.2.1 specifically). I changed to working with socket.io.engine.id instead. 

I peaked at the code for this PR and notice that the new easier to get to socket.id uses the same value. The question is wether the new socket.id is better to use, once it becomes available? I noticed the code handles updating of the value upon reconnect etc. Is that not the case with socket.io.engine.id?

**Comment by rauchg** [comment]
`socket.id` is added!

**Comment by davidrinnan** [comment]
ah of course. I can see it now in 1.3.0 
thanks!

**Pull request merged**
