### PR TITLE
Use the same onack logic on client side what server uses.

### PR DESCRIPTION
**Pull request by lattmann**
Might be related to these issues: #583 #716

Our use case could be totally irrelevant, but it was generating script errors in the browsers.

Relevant changes are in `lib/socket.js`, ack is called multiple times for the same packet id. After the first one the callback function is removed, then for the second time it fails on this line:
https://github.com/Automattic/socket.io-client/blob/master/lib/socket.js#L301 because `fn` is undefined.

We used this code:
https://github.com/Automattic/socket.io/blob/master/lib/socket.js#L365-L374

Both `socket.io` and `socket.io-client` packages are installed in our project. Both of them are also dependencies in our project.

Please feel free to change this description as needed.

-----------------------------------
I am not sure this is 'the' solution for the problem. It could be the case that we just have not configured karma or socket io correctly, but after spending hours on it, we just forked the repo and tried our tests with the changes in this pull request.

Use case:
We are using karma to run client side tests in the browser. Karma uses socket.io client 0.9.x we use 1.3.5. From the browsers we directly connect to our webserver. Karma is running on `localhost:9876` our webserver is running on `localhost:9001`.
Browsers: chrome and firefox.

Sometimes we saw an error that mentioned `apply` cannot be called on undefined. 

If we run the tests multiple times (leaving karma and our web server running) then we saw this error more frequently for multiple tests.

Our understanding is that karma uses websockets too.

If you think this issue belongs to another project we will report it there.

### CODE REVIEW

**Comment by rauchg** [comment]
Please don't submit the built `socket.io.js`

**Comment by lattmann** [comment]
Sorry, i did not know who should build it, and it was not in `.gitignore`. I have reverted the changes back to where i started this work. The diff now should be clean. Will do it this way in the future. Thanks.

**Comment by rauchg** [comment]
Thanks @lattmann

**Comment by rauchg** [comment]
We also use two spaces for indent :D

**Comment by lattmann** [comment]
Sorry, my editor is configured to pick up `.jshintrc` and `.jscsrc`. Otherwise it uses my global settings. I have changed to use 2 spaces for indentation.

Btw: where are the contributing guide lines? I have not found it in the repository. I would like to read it to avoid these issues in the future. Would you please give me a pointer?

**Comment by rauchg** [comment]
@lattmann none yet. Trying to switch to automated styling soon.

**Comment by rauchg** [comment]
ie: we shouldn't bother PR submitters like this.

**Comment by rauchg** [comment]
😨

**Comment by lattmann** [comment]
Ok, sounds good. Can you give us an estimate when you are planning to do your next release?

Thanks.

**Comment by rauchg** [comment]
ASAP, working on `1.4`

**Comment by lattmann** [comment]
Excellent, thanks.

**Comment by lattmann** [comment]
@rauchg do you have any news on the new release?

**Comment by Mokto** [comment]
+1 for this.

Got the same error on some events with react-native.

**Comment by lattmann** [comment]
You may like to try https://github.com/lattmann/socket.io-client/tree/1.3.6-patch_on_ack_fix because there is no official socket-io release yet for the `on_ack` issue. I keep pulling the latest release and apply this patch in my repo.

It may or may not fix your issue.

**Comment by Mokto** [comment]
Thanks !

Your fix is what I did to solve my issue. Waiting for an official release anyway :)

**Pull request merged**
